package com.edgar.domain;

import com.edgar.core.repository.Persistable;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.hibernate.validator.constraints.NotEmpty;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
public class Test2Table implements Persistable<Map<String, Object>>
{

	private static final long serialVersionUID = 1L;

	@NotEmpty
	@Size (max = 32)
	private String testId;

	@NotEmpty
	@Size (max = 32)
	private String testCode2;

	@NotEmpty
	@Size (max = 32)
	private String dictName;

	@NotEmpty
	@Size (max = 32)
	private String parentCode = "-1";

	@NotNull
	private Integer sorted = 9999;


	public Test2Table ()
	{

	}

	public Map<String, Object> getId()
	{
		Map<String, Object> mapping = new HashMap<String, Object>();
		mapping.put("test_code2",testCode2);
		mapping.put("test_id",testId);
		return Collections.unmodifiableMap(mapping);
	}

	public void setTestId (String testId)
	{
		this.testId = testId;
	}

	public String getTestId ()
	{
		return this.testId;
	}

	public void setTestCode2 (String testCode2)
	{
		this.testCode2 = testCode2;
	}

	public String getTestCode2 ()
	{
		return this.testCode2;
	}

	public void setDictName (String dictName)
	{
		this.dictName = dictName;
	}

	public String getDictName ()
	{
		return this.dictName;
	}

	public void setParentCode (String parentCode)
	{
		this.parentCode = parentCode;
	}

	public String getParentCode ()
	{
		return this.parentCode;
	}

	public void setSorted (Integer sorted)
	{
		this.sorted = sorted;
	}

	public Integer getSorted ()
	{
		return this.sorted;
	}

	@Override
	public String toString () 
	{
		return ToStringBuilder.reflectionToString (this); 
	}

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}