package com.edgar.repository;

import com.edgar.core.repository.BaseMapper;
import org.springframework.stereotype.Repository;
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;
import com.edgar.domain.CompanyConfig;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
@Repository
public interface CompanyConfigMapper extends BaseMapper<CompanyConfig, Integer>
{

	final static Logger logger = LoggerFactory.getLogger (CompanyConfigMapper.class);

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
    int count();

    void createTable();

    void dropTable();
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}

