package com.edgar.mapper;

import com.edgar.core.repository.BaseMapper;
import com.edgar.domain.TestTable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
public interface TestTableMapper extends BaseMapper<TestTable, String>
{

	final static Logger logger = LoggerFactory.getLogger(TestTableMapper.class);

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}

