package com.edgar.mapper;

import com.edgar.core.repository.BaseMapper;
import com.edgar.domain.Test2Table;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Map;

/**
 * This class is generated by Spring Data Jdbc code generator.
 *
 * @author Spring Data Jdbc Code Generator
 */
public interface Test2TableMapper extends BaseMapper<Test2Table, Map<String, Object>>
{

	final static Logger logger = LoggerFactory.getLogger(Test2TableMapper.class);

	/* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
    int count();

    void createTable();

    void dropTable();
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/

}

